version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'oasis2022'
    ports:
      - 7432:5432
    command:
      --max_connections=4800
    networks:
      default:
        ipv4_address: 192.168.20.4
    volumes:
      - db_data:/var/lib/postgresql/blockscout_data

  blockscout:
    container_name: 'blockscout'
    depends_on:
      - db
    image: blockscout/blockscout:pr-ac35e993
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "SPK"
        CACHE_EXCHANGE_RATES_PERIOD: ""
        DISABLE_READ_API: "false"
        API_PATH: "/"
        NETWORK_PATH: "/"
        DISABLE_WEBAPP: "false"
        DISABLE_WRITE_API: "false"
        CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        SOCKET_ROOT: "/"
        WOBSERVER_ENABLED: "false"
        ADMIN_PANEL_ENABLED: ""
    restart: always
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      - ./envs/dev-common-blockscout.env
    ports:
      - 4001:4000
    networks:
      default:
        ipv4_address: 192.168.20.5
networks:
  default:
    external:
      name: browser

volumes:
  db_data:
